#!/bin/zsh
if [ ! -f README.md ]; then
    echo "Run from project root folder!" >&2
    exit 1
fi

echo "Running Fixture Predictor"

# variables are  
# --executeFixtureAnalysis <first gameweek> <number of gameweeks to analyse>
# --previousPicks <team names/abbreviations that were used from the first gameweek onewards>...
#
# for instance:
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL LIV
#
# starts the analysis starting in GW1, covering 8 gameweeks (so GW1-GW8) 
# with GW1 being fixed on AVL and GW2 on LIV
# dotnet run --executeFixtureAnalysis 1 6
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL

# Season 2023/24, Game 1

# Jo
# GW2 Depth 6, best 0.300:  NEW 1.000  TOT 0.802  CHE 0.574  MCI 0.476  LIV 0.418  ARS 0.300
# GW2 Depth 8, best 0.169:  NEW 1.000  TOT 0.802  BRE 0.534  che 0.404  LEI 0.293  liv 0.242  ARS 0.200  mci 0.169
# GW2 Depth 10, best 0.079:  NEW 1.000  TOT 0.802  BRE 0.534  che 0.404  LEI 0.293  liv 0.242  ARS 0.200  MUN 0.142  MCI 0.127  SOU 0.079
dotnet run --executeFixtureAnalysis 1 12 --previousPicks NEW TOT BRE
