#!/bin/zsh
if [ ! -f README.md ]; then
    echo "Run from project root folder!" >&2
    exit 1
fi

echo "Running Fixture Predictor"

# variables are  
# --executeFixtureAnalysis <first gameweek> <number of gameweeks to analyse>
# --previousPicks <team names/abbreviations that were used from the first gameweek onewards>...
#
# for instance:
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL LIV
#
# starts the analysis starting in GW1, covering 8 gameweeks (so GW1-GW8) 
# with GW1 being fixed on AVL and GW2 on LIV
# dotnet run --executeFixtureAnalysis 1 6
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL

# Season 2023/24, Game 1

# Matt
# GW2 Depth 10, best 0.061:  ARS 1.000  TOT 0.802  BRE 0.534  che 0.404  LIV 0.355  BOU 0.215  LEI 0.155  MUN 0.110  MCI 0.098  SOU 0.061 
# GW2 Depth 8, best 0.147:  ARS 1.000  TOT 0.802  BRE 0.534  che 0.404  LEI 0.293  liv 0.242  MCI 0.206  MUN 0.147 
# GW2 Depth 6, best 0.285:  ARS 1.000  TOT 0.802  CHE 0.574  MCI 0.476  LEI 0.345  liv 0.285  
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks IPS SOU LEI WOL CRY EVE AVL ARS
dotnet run --executeFixtureAnalysis 21 9 --callrate 0

#--previousPicks LIV ARS 

# Reduce ELO by draw %
# Increase K factor to more favour form streams

#            10     11
# LIV ARS 0.192     0.134
# LIV AVL 0.227     0.178

# MCI ARS 0.223     0.115
# MCI AVL 0.264     0.207

# Combinations
# LIV ARS + MCI AVL = 0.456 (10) or 0.341 (11)
# LIV AVL + MCI ARS = 0.450 (10) or 0.293 (11)