#!/bin/zsh
if [ ! -f README.md ]; then
    echo "Run from root folder!" >&2
    exit 1
fi
echo "Running League of Ordinary Gentlemen Summary"
dotnet run --leagueId 6190 --incManagersInCaptaincy --callrate 0