#!/bin/zsh
if [ ! -f README.md ]; then
    echo "Run from project root folder!" >&2
    exit 1
fi

echo "Running Export CSV for AI"

# --executeExportForAI <gameweekToAnalyse>

dotnet run --exportForAI 29
