#!/bin/zsh
if [ ! -f README.md ]; then
    echo "Run from project root folder!" >&2
    exit 1
fi

echo "Running Fixture Predictor"

# variables are  
# --executeFixtureAnalysis <first gameweek> <number of gameweeks to analyse>
# --previousPicks <team names/abbreviations that were used from the first gameweek onewards>...
#
# for instance:
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL LIV
#
# starts the analysis starting in GW1, covering 8 gameweeks (so GW1-GW8) 
# with GW1 being fixed on AVL and GW2 on LIV
#dotnet run --executeFixtureAnalysis 1 8
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks AVL
# dotnet run --executeFixtureAnalysis 1 8 --previousPicks NEW ARS
dotnet run --executeFixtureAnalysis 3 2